dist: trusty
sudo: false
group: beta
language: bash
cache:
  directories:
    - $HOME/perl5
    - $HOME/git
    - $HOME/.m2
addons:
  apt:
    sources:
    - r-packages-trusty
    packages:
    - libxml2-utils
    - xsltproc
    - r-base
before_install:
  # R dependencies i.e. aleph-processor and bibliographica
  - echo "options(repos = c(CRAN = "https://cloud.r-project.org"))" >$HOME/.Rprofile
  - pushd $HOME/git
  - if [ ! -d aleph-processor ]; then git clone --depth 1 https://github.com/COMHIS/aleph-processor.git; fi
  - pushd aleph-processor
  - R -e "0" --args --bootstrap-packrat
  - popd
  - popd
  # Perl dependencies i.e. Catmandu
  - curl -L https://cpanmin.us | perl - -l ~/perl5 App::cpanminus local::lib
  - eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`
  - echo 'eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`' >> ~/.profile
  - cpanm Catmandu Catmandu::MARC
  # Apache Jena dependency
  - wget https://repository.apache.org/content/repositories/releases/org/apache/jena/apache-jena/3.1.1/apache-jena-3.1.1.tar.gz -O /tmp/apache-jena-3.1.1.tar.gz
  - tar -xzf /tmp/apache-jena-3.1.1.tar.gz
  - export PATH=$PATH:$PWD/apache-jena-3.1.1/bin/
  # marc2bibframe2 dependency
  - git clone --depth 1 --branch v1.2.0 https://github.com/lcnetdev/marc2bibframe2.git ../marc2bibframe2
  # hdt-cpp dependency
  # first we need serd...
  - mkdir -p $HOME/local
  - export PATH=$PATH:$HOME/local/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib
  - curl -s http://download.drobilla.net/serd-0.24.0.tar.bz2 | tar -xj
  - pushd serd-* && ./waf configure --prefix=$HOME/local && ./waf && ./waf install && popd 
  # ...then actual hdt-cpp
  - pushd $HOME/git
  - if [ ! -d hdt-cpp ]; then git clone --depth 1 https://github.com/rdfhdt/hdt-cpp.git; fi
  - cd hdt-cpp
  - git pull
  - make -C hdt-lib RAPTOR_SUPPORT=false LIBZ_SUPPORT=false LDFLAGS='-L${HOME}/local/lib -I${HOME}/local/include'
  - ln -s $PWD/hdt-lib/tools/* $HOME/local/bin
  - popd
  # hdt-java dependency
  - pushd $HOME/git
  - if [ ! -d hdt-java ]; then git clone --depth 1 https://github.com/rdfhdt/hdt-java.git; fi
  - pushd hdt-java && git pull && mvn install && cd hdt-java-package && mvn assembly:single && popd
  - ln -s $PWD/hdt-java/hdt-java-package/target/hdt-java-package-*-distribution/hdt-java-package-* $HOME/local/hdt-java-package
  - export PATH=$PATH:$HOME/local/hdt-java-package/bin
  - popd
script:
  - cd test
  - travis_wait 20 bats .
