dist: trusty
sudo: false
group: beta
language: bash
cache:
  directories:
    - $HOME/perl5
addons:
  apt:
    packages:
    - libxml2-utils
before_install:
  # Perl dependencies i.e. Catmandu
  - curl -L https://cpanmin.us | perl - -l ~/perl5 App::cpanminus local::lib
  - eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`
  - echo 'eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`' >> ~/.profile
  - cpanm Catmandu Catmandu::MARC
  # Apache Jena dependency
  - wget https://repository.apache.org/content/repositories/releases/org/apache/jena/apache-jena/3.1.1/apache-jena-3.1.1.tar.gz -O /tmp/apache-jena-3.1.1.tar.gz
  - tar -xzf /tmp/apache-jena-3.1.1.tar.gz
  - export PATH=$PATH:$PWD/apache-jena-3.1.1/bin/
  # marc2bibframe dependency
  - git clone https://github.com/lcnetdev/marc2bibframe.git ../marc2bibframe
  # marc2bibframe-wrapper dependency
  - mkdir -p ../marc2bibframe-wrapper/target/
  - wget https://github.com/NatLibFi/marc2bibframe-wrapper/releases/download/v0.0.1/marc2bibframe-wrapper-0.0.1.jar -O ../marc2bibframe-wrapper/target/marc2bibframe-wrapper-0.0.1.jar
  # hdt-cpp dependency
  - git clone https://github.com/rdfhdt/hdt-cpp.git
  - make -C hdt-cpp/hdt-lib
  - export PATH=$PATH:$PWD/hdt-cpp/hdt-lib/tools
script:
  - cd test
  - bats .
