dist: trusty
sudo: false
group: beta
language: bash
cache:
  directories:
    - perl_modules
before_install:
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  - cpanm Catmandu Catmandu::MARC
  - wget https://repository.apache.org/content/repositories/releases/org/apache/jena/apache-jena/3.1.1/apache-jena-3.1.1.tar.gz -O /tmp/apache-jena-3.1.1.tar.gz
  - tar -xzf /tmp/apache-jena-3.1.1.tar.gz
  - export PATH=$PATH:$PWD/apache-jena-3.1.1/bin/
script:
  - bats test
