dist: trusty
sudo: false
group: beta
language: bash
cache:
  directories:
    - $HOME/perl5
addons:
  apt:
    packages:
    - libxml2-utils
before_install:
  # Perl dependencies i.e. Catmandu
  - curl -L https://cpanmin.us | perl - -l ~/perl5 App::cpanminus local::lib
  - eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`
  - echo 'eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`' >> ~/.profile
  - cpanm Catmandu Catmandu::MARC
  # Apache Jena dependency
  - wget https://repository.apache.org/content/repositories/releases/org/apache/jena/apache-jena/3.1.1/apache-jena-3.1.1.tar.gz -O /tmp/apache-jena-3.1.1.tar.gz
  - tar -xzf /tmp/apache-jena-3.1.1.tar.gz
  - export PATH=$PATH:$PWD/apache-jena-3.1.1/bin/
  # marc2bibframe dependency
  - git clone https://github.com/lcnetdev/marc2bibframe.git ../marc2bibframe
  # marc2bibframe-wrapper dependency
  - mkdir -p ../marc2bibframe-wrapper/target/
  - wget https://github.com/NatLibFi/marc2bibframe-wrapper/releases/download/v0.0.1/marc2bibframe-wrapper-0.0.1.jar -O ../marc2bibframe-wrapper/target/marc2bibframe-wrapper-0.0.1.jar
  # hdt-cpp dependency
  # first we need serd...
  - mkdir -p $HOME/local
  - curl -s http://download.drobilla.net/serd-0.24.0.tar.bz2 | tar -xj
  - pushd serd-* && ./waf configure --prefix=$HOME/local && ./waf && ./waf install && popd 
  # we need to use osma's fork until hdt-cpp PR#49 gets merged
  - git clone https://github.com/osma/hdt-cpp.git
  - make -C hdt-cpp/hdt-lib RAPTOR_SUPPORT=false LIBZ_SUPPORT=false LDFLAGS='-L${HOME}/local/lib -I${HOME}/local/include'
  - export LD_LIBRARY_PATH=$HOME/local/lib
  - export PATH=$PATH:$PWD/hdt-cpp/hdt-lib/tools
  # hdt-java dependency
  - git clone https://github.com/rdfhdt/hdt-java.git
  - cd hdt-java
  - mvn install
  - cd hdt-java-package
  - mvn assembly:single
  - cd ../..
  - ln -s $PWD/hdt-java/hdt-java-package/target/hdt-java-package-*-distribution/hdt-java-package-* hdt-java-package
  - export PATH=$PATH:$PWD/hdt-java-package/bin
script:
  - cd test
  - bats .
